name: go_router_builder_sample_workspace
sdkPath: .fvm/flutter_sdk

packages:
  - packages/app

scripts:
  analyze:
    exec: fvm flutter analyze . --fatal-infos
      
  lint:
    run: melos run analyze && melos run format

  format:
    run: fvm dart format --set-exit-if-changed packages
  
  build_runner:
    exec: fvm flutter packages pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: 'build_runner'

  test:
    exec: fvm flutter test
    select-package:
      dir-exists:
        - test

  test-ci:unit:
    exec: fvm flutter test --machine > test.json
    packageFilters:
      scope: 'app'

  test-ci:coverage:
    exec: fvm flutter test --coverage
    packageFilters:
      scope: 'app'

  test-ci:combine: melos exec "\$MELOS_ROOT_PATH/scripts/combine_test.sh"
